### ISSUE TITLE
nose is not installed automatically if not already installed 

### ISSUE THREAD

**Issue by deeptavker** [deeptavker/PySPH_Project#2]
>pip install pysph
>pysph test -v 
```
Traceback (most recent call last):
  File "/home/deep/miniconda3/bin/pysph", line 11, in <module>
    sys.exit(main())
  File "/home/deep/miniconda3/lib/python3.5/site-packages/pysph/tools/cli.py", line 70, in main
    args.func(extra)
  File "/home/deep/miniconda3/lib/python3.5/site-packages/pysph/tools/cli.py", line 30, in run_tests
    from nose.core import main
ImportError: No module named 'nose'
```

Same is the problem with `conda install -c tavkerdeep pysph`

Also, if we're using nose, it should be one of the requirements.  
Or is it standard procedure to not include testing frameworks as hard requirements because these are primarily for developers and not users. 

However, in the file requirements.txt file, following requirements are mentioned for pysph :
* numpy
* setuptools>=6.0
* Cython>=0.20
* mako
* nose>=1.0.0
* mock>=1.0
* ordereddict
* importlib
* unittest2
* argparse

Also, why is mpi4py not mentioned here even though it explicitly raises an error during `pysph test`
```
Failure: SkipTest (mpi4py not installed) ... SKIP: mpi4py not installed

----------------------------------------------------------------------
Ran 282 tests in 373.974s

OK (SKIP=8)
```

**Comment by deeptavker** [comment]
Need to learn various testing frameworks. 
[Python-testing](http://pythontesting.net/start-here/)

**Comment by deeptavker** [comment]
Also, if we're using nose, it should be one of the requirements.  
Or is it standard procedure to not include testing frameworks as hard requirements because these are primarily for developers and not users.
